attributes:
  metadata:
    label: "Detach Database Plugin"
    weight: 90
  yaml_additional_config:
    type: "textarea"
    weight: 52
    value: |
      #Uncomment to enable remote DB:
      #remote_db: '10.20.99.1'
      #remote_db_password: 'secret'
      custom_mysql_setup_class: 'galera'
    label: "Additional config"
    description: "Input must be valid YAML"
    regex:
      source: '.+'
      error: "This field should not be empty"
